### --- Bad Practice 8: Share the Hostâ€™s Network Namespace --- ###
version: '3.8'
services:
  myapp:
    image: ubuntu 
    network_mode: host
### ---------------------------------------------------------- ###
