### --- Best Practice 0: do not limit capabilities --- ###
version: '3.8'

services:
  insecure_service:
    image: alpine
    privileged: true  # This will grant the container all capabilities
