### --- Bad Practice 18: OS package is not pinned to a specific version --- ###

version: '3.8'

services:
  myservice:
    build: .
    image: ubuntu:latest
    container_name: ubuntu_container
    command: ["ubuntu", "echo", "Hello World"]
