FROM ubuntu:20.04

RUN apt-get update && apt-get install -y curl=7.68.0-1ubuntu2.6

#Bad example: curl bashing: downloading and executing a script directly
RUN curl -sL https://example.com/install.sh | bash

COPY myapp /usr/local/bin/

CMD ["/usr/local/bin/myapp"]
