### --- Good Practice 34: Ensure that container health is checked at runtime --- ###

services:
    web:
        image: alpine:3.19.0
        build:
          context: .
          # dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        healthcheck:
          test: curl --fail http://localhost:5000/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 3
          start_period: 60s