### --- Best Practice 31: Ensure that incoming container traffic is bound to a specific host interface --- ###
version: '3.8'

services:
  web_server:
    image: nginx:alpine
    ports:
      - "192.168.1.10:80:80"  
### ------------------------------------------------------------------------------------------------------ ###