### --- Best Practice 36: Ensure data exchanged between containers are encrypted on different nodes on the overlay network --- ###

networks:
  secure-overlay:
    driver: overlay
    driver_opts:
      encrypted: "true"  # Ensures the network is encrypted

services:
  service1:
    image: alpine:3.19.0
    networks:
      - secure-overlay
    deploy:
      replicas: 2  # Example: 2 replicas on different nodes
      placement:
        constraints: [node.role == worker]

  service2:
    image: alpine:3.19.0
    networks:
      - secure-overlay
    deploy:
      replicas: 2  # Example: 2 replicas on different nodes
      placement:
        constraints: [node.role == worker]

# You can add more services here