version: '3'
services:
  web:
    image: nginx:1.27.0
    build: .
    ### --- Good Practice 6: Map host port 80 to container port 8080 --- ###
    ports:
      - "80:8080"  
    ### ---------------------------------------------------------------- ###
