FROM ubuntu:20.04

RUN apt-get update && apt-get install -y curl=7.68.0-1ubuntu2.6

# -- Best practice 19: using COPY, which is more secure and simpler than ADD -- ##
COPY myapp /usr/local/bin/

CMD ["/usr/local/bin/myapp"]
