version: '3.8'  # Specify the version of the Docker Compose file

services:
  example_service:
    image: alpine
    cap_drop:
      - ALL  # Drop all capabilities
    cap_add:
      - CHOWN  # Add the CHOWN capability
