version: '3'
services:
  app1:
    image: myapp1:alpine
    networks:
      - app1_net

  app2:
    image: myapp2:alpine
    networks:
      - app2_net

  app3:
    image: myapp3:alpine
    networks:
      - app3_net

## -- Best practice 2: be mindful of inter-container connectivity -- ##
networks:
  app1_net:
    driver: bridge

  app2_net:
    driver: bridge

  app3_net:
    driver: bridge

  internal_net:
    internal: false
